version: '3.8'
services:
  songbook:
    build: .
    container_name: songbook-app
    ports:
      - "5065:3000"
    volumes:
      - ./songs:/app/songs                 # Map your local songs folder
      - ./public:/app/public               # MAP THE ENTIRE PUBLIC FOLDER (CSS & Fonts)
      - ./setlists.json:/app/setlists.json # Map your setlists
    restart: unless-stopped